In [6]:
# Coded by Yuan Tian at UAF 2021.01
import matplotlib.pyplot as plt
import numpy as np
from sympy.matrices import Matrix # symbolic math package
import scipy.linalg

In [36]:
print('example matrix (A.49):')
A =[ [3,1,9,4 ] ,[2 ,1 ,7 ,3 ],[ 5 ,2, 16, 7]]
A=np.array(A)
A1 = Matrix(A)
rref_mat, rref_ind = A1.rref() # Get both the RREF and the pivots
print('rref(A) (A.50)= \n', rref_mat)
Matrix(A).rref()[0]

example matrix (A.49):
rref(A) (A.50)= 
 Matrix([[1, 0, 2, 1], [0, 1, 3, 1], [0, 0, 0, 0]])


Matrix([
[1, 0, 2, 1],
[0, 1, 3, 1],
[0, 0, 0, 0]])

In [37]:

# relationship between two null spaces
nA1 = scipy.linalg.null_space(A)
# nA2 = scipy.linalg.null_space(A,'r')
# q = nA1\nA2
# nA1*q

print('basis vectors for null space (A.51):')
x1 = np.array([-2,-3,1 ,0]).reshape((4,1))
x2 = np.array([-1 ,-1 ,0 ,1]).reshape((4,1))

print('one choice of b for A*x = b (A.52)')
b = np.array([22 ,17 ,39] ).reshape(3,1)        # given
#b = randi(99,3,1)       # most b are in the null space
AB=np.hstack((A,b))
AB1= Matrix(AB)
rrefAB, rref_ind = AB1.rref()
rrefAB

basis vectors for null space (A.51):
one choice of b for A*x = b (A.52)


Matrix([
[1, 0, 2, 1, 5],
[0, 1, 3, 1, 7],
[0, 0, 0, 0, 0]])

In [39]:

# choice of b leads to adding x0 to the solution: p = xn + x0
# (set x3 = x4 = 0)
x0 = np.vstack((rrefAB[:2,4],np.array([0,0]).reshape((2,1))))

# given solution to Ax = b
p =np.array([1, 2, 1, 2])
# solve for s and t
st = np.linalg.pinv(np.hstack((x1,x2))) @(p.reshape((4,1)) - x0)

# choose the "one particular solution" as in Aster
print('solution vector p corresponds to this choice of s and t (A.53):')
s = st[0]
t = st[1]
print(t,p)
# Eq A.53
xn = s*x1 + t*x2
print('xn=')
print(xn)
print('p = xn + x0:')
p = xn + x0
print(p)
print('add another null space vector to p (A.54):')
s=2
t=3
#s=0 t=0
xn = s*x1 + t*x2
print('xn=')
print(xn)
print('xn + p:')
print(xn + p)

print('check A*p - b:')
print(A@p - b)
print('check A*(xn+p) - b:')
print(A@(xn+p) - b)

solution vector p corresponds to this choice of s and t (A.53):
[2.00000000000000] [1 2 1 2]
xn=
[[-4.00000000000000]
 [-5.00000000000000]
 [1.00000000000000]
 [2.00000000000000]]
p = xn + x0:
[[1.00000000000000]
 [2.00000000000000]
 [1.00000000000000]
 [2.00000000000000]]
add another null space vector to p (A.54):
xn=
[[-7]
 [-9]
 [ 2]
 [ 3]]
xn + p:
[[-6.00000000000000]
 [-7.00000000000000]
 [3.00000000000000]
 [5.00000000000000]]
check A*p - b:
[[0]
 [0]
 [0]]
check A*(xn+p) - b:
[[0]
 [0]
 [0]]
